### ISSUE TITLE
Error in rule map_reads

### ISSUE THREAD

**Issue by mervebduman** [theislab/bartseq-pipeline#3]
Hello!

I am a master's student at the Charité Berlin. I am using the BART-Seq technique for my master's thesis project but I get some errors through the pipeline. Could you please help me? 

Kind regards,
Merve

```
Error in rule map_reads:
    jobid: 10
    output: process/4-mapped/R1_001_S0_R1.tsv, process/4-mapped/R1_001_S0_R1_summary.txt
    shell:
        
		hisat2 			--threads 2 			--reorder 			-k 1 			-3 34 			-x process/1-index/amplicons/R1_001_S0 			--new-summary --summary-file process/4-mapped/R1_001_S0_R1_summary.txt 			-q -U process/3-tagged/R1_001_S0_R1.fastq.gz | 			grep -v "^@" - | 		cut -f3,10 --output-delimiter='	' > process/4-mapped/R1_001_S0_R1.tsv
		
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by flying-sheep** [comment]
See here for help with this: https://stackoverflow.com/a/67176454/247482

That answer is excellent and tells you where that might have come from and how you debug it.

If it turns out to be a problem with how the pipeline runs the command (and not e.g. memory or disk space), please comment here and we can reopen this issue and fix the pipeline.
